services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=Dev0pC#SPSC09
      - MARIADB_USER=spsc
      - MARIADB_PASSWORD=Dev0pC#1420;
      - MARIADB_DATABASE=spsc_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - "3306:3306"  
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.5
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=spsc
      - MOODLE_DATABASE_PASSWORD=Dev0pC#1420;
      - MOODLE_DATABASE_NAME=spsc_moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Dev0pC#1420;
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local  
     
      
